Repository penumbra-zone/penumbra, pull requests merged in 2024-03, with the labels that each got.

#3915 staking: 🧹 tidy `validator_store` imports
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
Labels: A-staking, C-chore

#3906 pcli: improve pcli ibc channel queries
  crates/bin/pcli/src/command/query/ibc_query.rs
Labels: A-IBC, C-enhancement

#3922 keys: 🍴 `SpendKeyBytes: From<[u8; SPENDKEY_LEN_BYTES]>`
  crates/core/keys/src/keys/spend.rs
Labels: A-shielded-crypto, C-enhancement

#3921 scripts: 🤓 update `protobuf-codegen` shebang
  deployments/scripts/protobuf-codegen
Labels: A-tooling, C-chore

#3917 Add unfilled field to SimulateTradeResponse
  crates/core/component/dex/src/component/rpc.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/dex/v1/dex.proto
Labels: protobuf-changes

#3927 penumbra: use `ibc-proto@0.41` and `ibc-types@0.12`
  Cargo.lock
  Cargo.toml
Labels: A-tooling, C-chore

#3932 scripts: ➕ `penumbra-fee` and `penumbra-stake` in rust docs
  crates/core/component/fee/Cargo.toml
  crates/core/component/fee/src/lib.rs
  deployments/scripts/rust-docs
  docs/rustdoc/index.html
Labels: C-bug, A-docs

#3939 chore: 🌱 document and tidy `penumbra-view`
  crates/view/src/client.rs
  crates/view/src/lib.rs
  crates/view/src/note_record.rs
  crates/view/src/planner.rs
  crates/view/src/service.rs
Labels: C-chore

#3949 dex: fix chain halt in testnet 68
  crates/core/component/dex/src/component/router/route_and_fill.rs
  crates/core/component/dex/src/swap_execution.rs
Labels: A-dex

#3950 dex: 🌸 apply "fix chain halt in testnet 68" to main
  crates/core/component/dex/src/component/router/route_and_fill.rs
  crates/core/component/dex/src/swap_execution.rs
Labels: C-bug, A-dex

#3952 pd: 📦 add a tracing event with cargo version
  crates/bin/pd/src/main.rs
Labels: A-telemetry

#3918 ibc: error on attempts to send packets with expired client
  crates/core/component/ibc/src/component/packet.rs
Labels: A-IBC

#3953 ibc: show client expiry status in channel query
  Cargo.lock
  crates/bin/pcli/Cargo.toml
  crates/bin/pcli/src/command/query/ibc_query.rs
Labels: A-IBC, C-enhancement

#3902 mock-consensus: 🌱 single genesis validator
  Cargo.lock
  crates/core/app/Cargo.toml
  crates/core/app/src/app/mod.rs
  crates/core/app/tests/common/mod.rs
  crates/core/app/tests/common/test_node_builder_ext.rs
  crates/core/app/tests/mock_consensus.rs
  crates/test/mock-consensus/Cargo.toml
  crates/test/mock-consensus/src/builder.rs
  crates/test/mock-consensus/src/builder/init_chain.rs
  crates/test/mock-consensus/src/keyring.rs
  crates/test/mock-consensus/src/lib.rs
Labels: C-enhancement, A-mock-consensus

#3969 chore(app): 🧹 tidy dependency list
  crates/core/app/Cargo.toml
Labels: C-chore

#3970 chore: update chain id to deimos-5
  testnets/069-deimos-5/allocations.csv
  testnets/069-deimos-5/validators.json
Labels: C-chore

#3971 view: 🌯 remove frivolous `Option::expect` call
  crates/view/src/storage.rs
Labels: A-client, C-refactor

#3975 chore(tendermint-proxy): 👆 tidy `tendermint-proxy` code
  crates/util/tendermint-proxy/src/tendermint_proxy.rs
Labels: C-chore

#3928 stake: fix missing index and simplify state machine
  crates/core/component/stake/src/component/action_handler/validator_definition.rs
  crates/core/component/stake/src/component/epoch_handler.rs
  crates/core/component/stake/src/component/stake.rs
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
Labels: A-staking, consensus-breaking

#3987 chore(gitignore): 🤔 ignore proposal.toml
  .gitignore
Labels: C-chore, A-testing

#3988 pd: 👄 log testnet directory reset
  crates/bin/pd/src/main.rs
Labels: C-chore, A-testing

#3989 tests(pcli): 🔇 make large tracing event trace-level
  crates/bin/pcli/tests/network_integration.rs
Labels: C-chore, A-testing

#3984 view(rpc): add `DelegationsByAddressIndex` query
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/proto/src/gen/penumbra.view.v1.rs
  crates/proto/src/gen/penumbra.view.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  crates/view/src/service.rs
  proto/penumbra/penumbra/view/v1/view.proto
Labels: protobuf-changes

#3996 refactor(pd): 🎬 pull grpc endpoint into `penumbra-app`
  Cargo.lock
  crates/bin/pd/src/main.rs
  crates/core/app/Cargo.toml
  crates/core/app/src/rpc.rs
  crates/core/app/src/rpc/query.rs
Labels: A-mock-consensus, C-refactor

#4002 mock-consensus: 🔀 test node can `fast_forward`
  crates/core/app/tests/mock_consensus.rs
  crates/test/mock-consensus/src/lib.rs
Labels: A-mock-consensus

#4004 mock-consensus: 👷 block data is implicitly empty, can be appended
  crates/test/mock-consensus/src/block.rs
  crates/test/mock-consensus/src/lib.rs
Labels: A-mock-consensus

#4010 app: 🤓 fix grammar in comment
  crates/core/app/src/app/mod.rs
Labels: A-docs, C-chore

#4009 refactor(staking): 😊 tracing telemetry for delegation changes
  crates/core/component/stake/src/component/stake.rs
Labels: A-staking, A-telemetry, C-refactor

#4011 app: 🦅 `Consensus::end_block` never errors
  crates/core/app/src/server/consensus.rs
Labels: A-node, C-refactor

#4012 app: add `assert!` to dummy spend test
  crates/core/app/tests/spend.rs
Labels: C-bug, A-testing

#3923 staking: use block height to enforce unbonding delay
  Cargo.lock
  crates/bin/pcli/src/command/query/chain.rs
  crates/bin/pcli/src/command/tx.rs
  crates/bin/pcli/tests/proof.rs
  crates/bin/pd/src/testnet/generate.rs
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/core/app/src/params/change.rs
  crates/core/asset/src/asset/registry.rs
  crates/core/component/shielded-pool/src/component/shielded_pool.rs
  crates/core/component/stake/src/component/action_handler/delegate.rs
  crates/core/component/stake/src/component/action_handler/undelegate.rs
  crates/core/component/stake/src/component/action_handler/undelegate_claim.rs
  crates/core/component/stake/src/component/action_handler/validator_definition.rs
  crates/core/component/stake/src/component/epoch_handler.rs
  crates/core/component/stake/src/component/stake.rs
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
  crates/core/component/stake/src/params.rs
  crates/core/component/stake/src/rate.rs
  crates/core/component/stake/src/unbonding_token.rs
  crates/core/component/stake/src/undelegate.rs
  crates/core/component/stake/src/undelegate_claim/action.rs
  crates/core/component/stake/src/undelegate_claim/plan.rs
  crates/core/component/stake/src/validator/bonding.rs
  crates/proto/src/gen/penumbra.core.component.stake.v1.rs
  crates/proto/src/gen/penumbra.core.component.stake.v1.serde.rs
  crates/proto/src/gen/penumbra.view.v1.rs
  crates/proto/src/gen/penumbra.view.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  crates/view/src/planner.rs
  crates/view/src/service.rs
  crates/wallet/Cargo.toml
  crates/wallet/src/plan.rs
  proto/penumbra/penumbra/core/component/stake/v1/stake.proto
  proto/penumbra/penumbra/view/v1/view.proto
Labels: A-staking, consensus-breaking, protobuf-changes, state-breaking

#4017 staking: 🎁 add additional tracing telemetry
  crates/core/app/src/app/mod.rs
  crates/core/component/compact-block/src/component/manager.rs
  crates/core/component/stake/src/component/action_handler/delegate.rs
  crates/core/component/stake/src/component/epoch_handler.rs
  crates/core/component/stake/src/component/mod.rs
  crates/core/component/stake/src/component/stake.rs
  crates/core/component/stake/src/lib.rs
Labels: A-staking, C-enhancement, A-telemetry, A-mock-consensus, C-refactor

#3954 docs: update deimos ibc channel for osmosis
  docs/guide/book.toml
  docs/guide/src/dev/ibc.md
  docs/guide/src/pcli/transaction.md
Labels: A-IBC, C-enhancement, A-docs

#4020 shielded-pool: delegate supply tracking to components
  crates/core/app/src/action_handler/actions/submit.rs
  crates/core/component/governance/src/action_handler/deposit_claim.rs
  crates/core/component/governance/src/action_handler/withdraw.rs
  crates/core/component/governance/src/component/view.rs
  crates/core/component/shielded-pool/src/component.rs
  crates/core/component/shielded-pool/src/component/assets.rs
  crates/core/component/shielded-pool/src/component/note_manager.rs
  crates/core/component/shielded-pool/src/component/rpc.rs
  crates/core/component/shielded-pool/src/component/shielded_pool.rs
  crates/core/component/shielded-pool/src/component/supply.rs
  crates/core/component/shielded-pool/src/component/transfer.rs
  crates/core/component/shielded-pool/src/state_key.rs
  crates/core/component/stake/src/component/action_handler/undelegate.rs
  crates/core/component/stake/src/component/action_handler/validator_definition.rs
  crates/core/component/stake/src/component/epoch_handler.rs
  crates/core/component/stake/src/component/stake.rs
  crates/core/component/stake/src/component/validator_handler.rs
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
  crates/core/component/stake/src/identity_key.rs
  crates/core/component/stake/src/state_key.rs
Labels: A-IBC, A-staking, zellic-component-remediated, consensus-breaking, state-breaking

#4026 docs: bump penumbra version in docs to v0.69.1
  docs/guide/src/penumbra_version.md
Labels: A-docs

#4031 fix(pd): rename unbonding epochs -> delay
  crates/bin/pd/src/cli.rs
  crates/bin/pd/src/main.rs
  crates/bin/pd/src/testnet/generate.rs
  deployments/scripts/smoke-test.sh
Labels: A-node, C-bug

#4032 docs: update cometbft version to v0.37.5
  COMPATIBILITY.md
  docs/guide/src/cometbft_version.md
  docs/guide/src/pd/debugging.md
Labels: C-enhancement, A-docs

#4034 ci: add dedicated indexer node for gov dashboard
  deployments/helmfile.d/penumbra-testnet.yaml
Labels: A-governance

#4001 tests: 🏃 mock consensus can exercise staking component
  crates/core/app/tests/common/mod.rs
  crates/core/app/tests/common/test_node_builder_ext.rs
  crates/core/app/tests/mock_consensus_staking.rs
  crates/core/component/stake/src/component/action_handler/validator_definition.rs
  crates/core/component/stake/src/component/stake.rs
  crates/test/mock-consensus/src/block.rs
  crates/test/mock-consensus/src/builder.rs
  crates/test/mock-consensus/src/builder/init_chain.rs
  crates/test/mock-consensus/src/keyring.rs
  crates/test/mock-consensus/src/lib.rs
Labels: A-mock-consensus

#4039 refactor(mock-consensus): 🔐 remove `Keyring`
  crates/test/mock-consensus/src/builder.rs
  crates/test/mock-consensus/src/keyring.rs
  crates/test/mock-consensus/src/lib.rs
Labels: A-mock-consensus, C-refactor

#4041 staking: change `compute_unbonding_height` api
  crates/core/component/stake/src/component/action_handler/undelegate_claim.rs
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
  crates/core/component/stake/src/rate.rs
  crates/core/component/stake/src/validator.rs
Labels: A-staking, consensus-breaking

#4042 chore(cargo.toml): 🧹 sort workspace members
  Cargo.toml
Labels: C-chore

#4043 chore(pd): 🤏 sort and tidy `Cargo.toml`
  crates/bin/pd/Cargo.toml
Labels: C-chore

#4048 tests(app): ⌛ shorten epoch length in staking test
  crates/core/app/tests/mock_consensus_staking.rs
  crates/test/mock-consensus/src/lib.rs
Labels: A-mock-consensus

#4051 docs: dev guide notes on asset ids in sqlite3
  docs/guide/src/dev/sql.md
Labels: C-enhancement, A-docs

#4057 staking(undelegate): remove obsolete comment in balance impl
  crates/core/component/stake/src/penalty.rs
  crates/core/component/stake/src/undelegate.rs
Labels: A-staking

#4059 tests(app): 🍖 compare new and existing validator rates
  crates/core/app/tests/mock_consensus_staking.rs
Labels: C-enhancement, A-testing, A-mock-consensus

#4069 ci: automatic deployments of standalone nodes
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-standalone.yml
  .github/workflows/deploy-testnet.yml
Labels: C-enhancement, A-CI/CD

#4066 dex: add DexParameters, remove RoutingParams::default()
  Cargo.lock
  crates/bin/pcli/src/command/tx/proposal.rs
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/core/app/src/app/mod.rs
  crates/core/app/src/params.rs
  crates/core/app/src/params/change.rs
  crates/core/component/dex/src/circuit_breaker/value.rs
  crates/core/component/dex/src/component/arb.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/router/params.rs
  crates/core/component/dex/src/component/router/tests.rs
  crates/core/component/dex/src/component/rpc.rs
  crates/core/component/dex/src/component/tests.rs
  crates/core/component/dex/src/genesis.rs
  crates/core/component/dex/src/lib.rs
  crates/core/component/dex/src/params.rs
  crates/core/component/dex/src/state_key.rs
  crates/core/component/governance/Cargo.toml
  crates/core/component/governance/src/proposal.rs
  crates/core/component/sct/src/component/sct.rs
  crates/core/genesis/Cargo.toml
  crates/core/genesis/src/lib.rs
  crates/proto/src/gen/penumbra.core.app.v1.rs
  crates/proto/src/gen/penumbra.core.app.v1.serde.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.serde.rs
  crates/proto/src/gen/penumbra.core.component.governance.v1.rs
  crates/proto/src/gen/penumbra.core.component.governance.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/app/v1/app.proto
  proto/penumbra/penumbra/core/component/dex/v1/dex.proto
  proto/penumbra/penumbra/core/component/governance/v1/governance.proto
Labels: A-dex

#4062 ci: use mdbook-linkcheck for docs linting
  .github/workflows/docs-lint.yml
  .github/workflows/notes.yml
  .github/workflows/rust.yml
  docs/guide/book.toml
  docs/protocol/book.toml
Labels: A-CI/CD

#4072 chore(staking): 🧹 tidy `validator_manager` imports
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
Labels: A-staking, C-chore

#4068 staking: add delay to reenable a validator
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
  crates/core/component/stake/src/state_key.rs
Labels: A-staking, zellic-component-remediated, consensus-breaking

#4074 ci: disable readinessProbes in maintenanceMode
  deployments/charts/penumbra-network/templates/statefulset.yaml
  deployments/charts/penumbra-node/templates/statefulset.yaml
Labels: A-CI/CD, C-chore

#4053 cnidarium: use incremental jmt migration
  Cargo.lock
  Cargo.toml
  crates/cnidarium/Cargo.toml
  crates/cnidarium/src/storage.rs
  crates/cnidarium/src/store/multistore.rs
  crates/cnidarium/src/store/substore.rs
  crates/cnidarium/tests/migration.rs
Labels: A-upgrades

#4055 feat(pd): support archives for migrate and join
  Cargo.lock
  crates/bin/pd/Cargo.toml
  crates/bin/pd/src/cli.rs
  crates/bin/pd/src/main.rs
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/testnet/join.rs
Labels: A-upgrades

#4086 dex: redesign value circuit breaker
  crates/core/component/dex/src/circuit_breaker/mod.rs
  crates/core/component/dex/src/circuit_breaker/value.rs
  crates/core/component/dex/src/component/action_handler/position/open.rs
  crates/core/component/dex/src/component/action_handler/position/withdraw.rs
  crates/core/component/dex/src/component/action_handler/swap.rs
  crates/core/component/dex/src/component/arb.rs
  crates/core/component/dex/src/component/circuit_breaker/execution.rs
  crates/core/component/dex/src/component/circuit_breaker/mod.rs
  crates/core/component/dex/src/component/circuit_breaker/value.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/mod.rs
  crates/core/component/dex/src/component/position_manager.rs
  crates/core/component/dex/src/component/router/route_and_fill.rs
  crates/core/component/dex/src/component/router/tests.rs
  crates/core/component/dex/src/component/rpc.rs
  crates/core/component/dex/src/component/tests.rs
  crates/core/component/dex/src/event.rs
  crates/core/component/dex/src/lib.rs
  crates/core/component/dex/src/lp/position.rs
  crates/core/component/dex/src/state_key.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/dex/v1/dex.proto
Labels: zellic-component-remediated, consensus-breaking, A-dex, state-breaking

#4094 cnidarium: use `WriteBatch` when writing jmt nodes
  crates/cnidarium/src/storage.rs
  crates/cnidarium/src/store/substore.rs
Labels: A-node, C-bug

#4099 refactor(staking): 🌹 hoist uptime tracking into `ValidatorUptimeTracker` extension trait
  crates/core/component/stake/src/component/stake.rs
  crates/core/component/stake/src/component/stake/address.rs
  crates/core/component/stake/src/component/validator_handler.rs
  crates/core/component/stake/src/component/validator_handler/uptime_tracker.rs
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
Labels: A-staking, A-mock-consensus

#4100 compact block: add epoch index to compact block
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/core/component/compact-block/src/compact_block.rs
  crates/core/component/compact-block/src/component/manager.rs
  crates/proto/src/gen/penumbra.core.component.compact_block.v1.rs
  crates/proto/src/gen/penumbra.core.component.compact_block.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/compact_block/v1/compact_block.proto
Labels: consensus-breaking

#4102 staking: 🏁 ex post facto #4099 review comments
  crates/core/component/stake/src/component/validator_handler/uptime_tracker.rs
Labels: A-staking

#4103 tests(app): 🌯 reorganize, rename mock consensus integration tests
  crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs
  crates/core/app/tests/app_can_spend_notes_and_detect_outputs.rs
  crates/core/app/tests/init_chain.rs
Labels: C-chore, A-testing, A-mock-consensus

#4104 app: check asset id in fee stateful check
  crates/core/app/src/action_handler/transaction/stateful.rs
Labels: A-node, C-bug, zellic-component-needs-remediation, consensus-breaking

#4101 ibc: use outbound_ics20_transfers_enabled chain parameter
  crates/core/app/src/action_handler/actions.rs
Labels: A-IBC, consensus-breaking

#4115 feat(transaction): 📩 `ActionPlan: From<UndelegateClaimPlan>`
  crates/core/transaction/src/plan/action.rs
Labels: A-tooling

#4097 docs: chain upgrade procedure, for operators
  docs/guide/src/SUMMARY.md
  docs/guide/src/pd/chain-upgrade.md
  docs/guide/src/pd/join-testnet.md
Labels: A-docs, A-upgrades

#4119 proto(view): deprecate `start_epoch_index`
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/proto/src/gen/penumbra.view.v1.rs
  crates/proto/src/gen/penumbra.view.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/view/v1/view.proto
Labels: protobuf-changes

#4127 app: increment halt counter
  COMPATIBILITY.md
  crates/core/app/src/app/mod.rs
  crates/core/app/src/lib.rs
Labels: A-node, A-upgrades

#4105 spec: flesh out more the encrypted parts of a tx
  crates/core/component/dex/src/swap/plaintext.rs
  docs/protocol/src/SUMMARY.md
  docs/protocol/src/addresses_keys/transaction_crypto.md
  docs/protocol/src/dex/action/swap.md
  docs/protocol/src/dex/action/swap_claim.md
  docs/protocol/src/shielded_pool/action/output.md
  docs/protocol/src/transactions.md
  docs/protocol/src/transactions/actions.md
  docs/protocol/src/transactions/memo.md
Labels: A-docs

#4117 ci: add component contract check
  .github/workflows/rust.yml
  deployments/scripts/check-wasm-compat.sh
Labels: A-wasm

#4140 Add missing `address_index` field to `UnbondingTokensByAddressIndexRequest`
  crates/proto/src/gen/penumbra.view.v1.rs
  crates/proto/src/gen/penumbra.view.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/view/v1/view.proto
Labels: protobuf-changes
