Repository penumbra-zone/penumbra, pull requests merged in 2024-06, with the labels that each got.

#4511 dex: evict excess of liquidity positions
  crates/core/component/compact-block/src/component/manager.rs
  crates/core/component/dex/src/component/action_handler/swap.rs
  crates/core/component/dex/src/component/arb.rs
  crates/core/component/dex/src/component/chandelier.rs
  crates/core/component/dex/src/component/circuit_breaker/value.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/eviction_manager.rs
  crates/core/component/dex/src/component/mod.rs
  crates/core/component/dex/src/component/position_manager.rs
  crates/core/component/dex/src/component/position_manager/counter.rs
  crates/core/component/dex/src/component/router/params.rs
  crates/core/component/dex/src/component/router/route_and_fill.rs
  crates/core/component/dex/src/component/router/tests.rs
  crates/core/component/dex/src/component/swap_manager.rs
  crates/core/component/dex/src/component/tests.rs
  crates/core/component/dex/src/state_key.rs
Labels: consensus-breaking, A-dex

#4521 dex: less awkward logging if no arbs are found
  crates/core/component/dex/src/component/arb.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/tests.rs
Labels: A-dex

#4524 dex: 🧮 shift dex buckets over by a factor of 1000
  crates/core/component/dex/src/component/metrics.rs
Labels: C-bug, A-telemetry, A-dex

#4518 Exclude IBC assets from TotalSupply if their denom metadata is nonexistent
  crates/core/component/shielded-pool/src/component/rpc/bank_query.rs
Labels: A-IBC, C-bug

#4473 Implement sliding window algorithm for FMD params
  crates/core/component/shielded-pool/src/component/shielded_pool.rs
  crates/core/component/shielded-pool/src/fmd.rs
  crates/core/component/shielded-pool/src/fmd/state_key.rs
  crates/crypto/decaf377-fmd/src/precision.rs
  crates/proto/src/gen/penumbra.core.component.shielded_pool.v1.rs
  crates/proto/src/gen/penumbra.core.component.shielded_pool.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/shielded_pool/v1/shielded_pool.proto
Labels: A-shielded-crypto, consensus-breaking

#4528 dex: 🌱 add a `SimulationsDisabled` stub for dex queries
  crates/core/app/src/rpc.rs
  crates/core/component/dex/src/component/rpc.rs
  crates/core/component/dex/src/component/rpc/stub.rs
Labels: A-dex

#4530 dex: 🧮 shift dex buckets over by a factor of 1000
  crates/core/component/dex/src/component/metrics.rs
Labels: A-telemetry, A-dex

#4539 feat(fee): add FromStr, Display impls for FeeTier
  crates/bin/pcli/src/command/tx.rs
  crates/bin/pcli/src/command/tx/auction/dutch.rs
  crates/bin/pcli/src/command/tx/liquidity_position.rs
  crates/bin/pcli/src/command/tx/proposal.rs
  crates/core/component/fee/src/fee.rs
Labels: A-fees

#4537 dex: backport arb execution metric fix to `v0.77.x`
  crates/core/component/dex/src/component/arb.rs
Labels: A-telemetry, A-dex

#4538 pcli: backport `staked` fix to `v0.77.x`
  crates/bin/pcli/src/command/view/staked.rs
  crates/view/src/planner.rs
Labels: A-client

#4542 backport penumbra-fee string impls for 0.77.x
  crates/bin/pcli/src/command/tx.rs
  crates/bin/pcli/src/command/tx/auction/dutch.rs
  crates/bin/pcli/src/command/tx/liquidity_position.rs
  crates/bin/pcli/src/command/tx/proposal.rs
  crates/core/component/fee/src/fee.rs
Labels: A-fees

#4544 pcli: show full params
  crates/bin/pcli/src/command/query/chain.rs
Labels: A-client, C-enhancement

#4492 spec: clarify UndelegateClaim in spec
  docs/protocol/src/stake/action/undelegate_claim.md
Labels: A-docs, ecc-component-remediated

#4575 ci: fix persistence for indexing dbs
  deployments/charts/penumbra-node/templates/statefulset.yaml
  deployments/charts/penumbra-node/values.yaml
Labels: A-CI/CD

#3501 feat: support display seed phrase discreetly
  crates/bin/pcli/src/command/init.rs
Labels: A-client, C-enhancement

#4580 pcli(gda): apply web fixes to pcli recipes
  Cargo.lock
  crates/bin/pcli/Cargo.toml
  crates/bin/pcli/src/command/tx/auction/dutch/gda.rs
Labels: A-auction

#4576 pcli: add options to pcli v address for displaying an FVK or generating a payment address from a provided FVK
  crates/bin/pcli/src/command/view/address.rs
Labels: A-client

#4581 pd: 💤 a sleep worker, tracking scheduler latency
  crates/bin/pd/src/lib.rs
  crates/bin/pd/src/main.rs
  crates/bin/pd/src/metrics.rs
  crates/bin/pd/src/metrics/sleep_worker.rs
Labels: A-telemetry

#4567 Enforce string limits for deserialization
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/migrate/reset_halt_bit.rs
  crates/bin/pd/src/migrate/testnet72.rs
  crates/bin/pd/src/migrate/testnet74.rs
  crates/bin/pd/src/migrate/testnet76.rs
  crates/bin/pd/src/migrate/testnet78.rs
  crates/bin/pd/src/testnet/generate.rs
  crates/core/component/governance/src/change.rs
  crates/core/component/governance/src/proposal.rs
  crates/core/component/governance/src/proposal_state.rs
  crates/core/component/governance/src/validator_vote/action.rs
  crates/core/component/stake/src/validator.rs
  crates/core/component/stake/src/validator/definition.rs
Labels: A-staking, A-governance, _P-V1, consensus-breaking, state-breaking, migration

#4597 pd: configure cometbft with `max_bytes` to 1MiB
  crates/bin/pd/src/testnet/generate.rs
Labels: A-node, C-bug

#4594 pd: use 10MB as mempool limit in comet config template
  testnets/cometbft_config_template.toml
Labels: C-design

#4606 Migration 78: Avoid deserializing proto types to domain types in migration
  crates/bin/pd/src/migrate/testnet78.rs
Labels: migration

#4564 dex: fold `Position`s into the price indexes
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/migrate/testnet78.rs
  crates/core/component/dex/src/component/circuit_breaker/value.rs
  crates/core/component/dex/src/component/position_manager.rs
  crates/core/component/dex/src/component/position_manager/base_liquidity_index.rs
  crates/core/component/dex/src/component/position_manager/counter.rs
  crates/core/component/dex/src/component/position_manager/inventory_index.rs
  crates/core/component/dex/src/component/position_manager/price_index.rs
  crates/core/component/dex/src/component/router/fill_route.rs
  crates/core/component/dex/src/component/router/path.rs
  crates/core/component/dex/src/component/router/tests.rs
  crates/core/component/dex/src/component/rpc.rs
  crates/core/component/dex/src/state_key.rs
Labels: consensus-breaking, A-dex, migration

#4617 pcli: 💿 crate can be used as a library
  crates/bin/pcli/src/lib.rs
  crates/bin/pcli/src/main.rs
Labels: A-client, C-enhancement, A-testing

#4523 sct(component): add `TimestampByHeight` to query service
  Cargo.lock
  crates/bin/pd/src/migrate.rs
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/core/app/src/penumbra_host_chain.rs
  crates/core/component/ibc/src/component/client.rs
  crates/core/component/ibc/src/component/packet.rs
  crates/core/component/sct/Cargo.toml
  crates/core/component/sct/src/component/clock.rs
  crates/core/component/sct/src/component/rpc.rs
  crates/core/component/sct/src/component/sct.rs
  crates/core/component/sct/src/state_key.rs
  crates/proto/src/gen/penumbra.core.component.sct.v1.rs
  crates/proto/src/gen/penumbra.core.component.sct.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/sct/v1/sct.proto
Labels: A-node, C-enhancement, protobuf-changes

#4449 Define staking events
  Cargo.lock
  crates/core/app/src/app/mod.rs
  crates/core/component/funding/Cargo.toml
  crates/core/component/funding/src/component.rs
  crates/core/component/funding/src/event.rs
  crates/core/component/funding/src/lib.rs
  crates/core/component/stake/src/component/action_handler/delegate.rs
  crates/core/component/stake/src/component/action_handler/undelegate.rs
  crates/core/component/stake/src/component/stake.rs
  crates/core/component/stake/src/component/validator_handler/uptime_tracker.rs
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
  crates/core/component/stake/src/event.rs
  crates/proto/src/gen/penumbra.core.component.funding.v1.rs
  crates/proto/src/gen/penumbra.core.component.funding.v1.serde.rs
  crates/proto/src/gen/penumbra.core.component.stake.v1.rs
  crates/proto/src/gen/penumbra.core.component.stake.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/funding/v1/funding.proto
  proto/penumbra/penumbra/core/component/stake/v1/stake.proto
Labels: A-staking, protobuf-changes

#4620 dex: fold execution budget in `DexParameters`
  crates/bin/pd/src/migrate/testnet78.rs
  crates/core/app/src/params/change.rs
  crates/core/component/dex/src/component/arb.rs
  crates/core/component/dex/src/component/circuit_breaker/execution.rs
  crates/core/component/dex/src/component/circuit_breaker/value.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/router/route_and_fill.rs
  crates/core/component/dex/src/component/router/tests.rs
  crates/core/component/dex/src/component/rpc.rs
  crates/core/component/dex/src/component/tests.rs
  crates/core/component/dex/src/params.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/dex/v1/dex.proto
Labels: consensus-breaking, A-dex, state-breaking, migration

#4615 proto: add spend to `TransactionPlannerRequest`
  crates/proto/src/gen/penumbra.view.v1.rs
  crates/proto/src/gen/penumbra.view.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  deployments/scripts/protobuf-codegen
  proto/penumbra/penumbra/view/v1/view.proto
Labels: protobuf-changes

#4622 Retrieve SwapExecutions from nonverifiable storage in RPC
  crates/core/component/dex/src/component/rpc.rs
Labels: A-node, A-dex

#4633 app(tests): disable flakey app tests for now
  crates/core/app/tests/app_can_sweep_a_collection_of_small_notes.rs
  crates/core/app/tests/view_server_can_be_served_on_localhost.rs
Labels: A-testing

#4570 crypto: check ck_d is consistent with d, pk_d provided on a note
  crates/core/component/shielded-pool/src/note.rs
Labels: A-shielded-crypto

#4636 ibc: prevent packet sends with timeout timestamp in the past
  crates/core/component/ibc/src/component/packet.rs
Labels: consensus-breaking

#4621 auction: dex-enabled check during LP allocation
  crates/core/component/auction/src/component/action_handler/dutch/schedule.rs
  crates/core/component/auction/src/component/dutch_auction.rs
  crates/core/component/dex/src/component/position_manager.rs
Labels: consensus-breaking, A-dex, A-auction

#4614 migration: update cometbft tx size for t78 migration
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/migrate/testnet78.rs
Labels: consensus-breaking

#4644 ibc: delete packet commitments instead of writing empty values
  crates/bin/pd/src/migrate/testnet78.rs
  crates/core/component/ibc/src/component/channel.rs
Labels: A-IBC, consensus-breaking, state-breaking, migration

#4651 staking: deprecate obsolete base reward rate field
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/core/app/src/params/change.rs
  crates/core/component/stake/src/params.rs
  crates/proto/src/gen/penumbra.core.component.stake.v1.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/stake/v1/stake.proto
Labels: A-staking, protobuf-changes

#4652 pd: 🙏 propagate errors from ACME worker
  crates/bin/pd/src/main.rs
  crates/util/auto-https/src/lib.rs
Labels: A-node, C-enhancement

#4638 ibc: fix timeouts: use client height and timestamp
  crates/core/component/ibc/src/component/msg_handler/timeout.rs
Labels: consensus-breaking

#4653 cnidarium: prefix queries over substores are hazardous
  crates/bin/pd/src/migrate/testnet78.rs
  crates/cnidarium/src/snapshot.rs
  crates/cnidarium/tests/substore_tests.rs
Labels: A-node, C-bug, consensus-breaking

#4627 app: drop stateful mempool
  crates/core/app/src/app/mod.rs
  crates/core/app/src/server/consensus.rs
  crates/core/app/src/server/mempool.rs
Labels: A-node, consensus-breaking

#4654 ibc: fix logging of timestamp timeouts
  crates/core/component/ibc/src/component/packet.rs
Labels: A-IBC

#4643 dex: Swap alt fee tokens for native fee token
  Cargo.lock
  crates/core/app/src/action_handler/transaction.rs
  crates/core/app/src/action_handler/transaction/stateful.rs
  crates/core/app/src/app/mod.rs
  crates/core/app/tests/app_check_dex_vcb.rs
  crates/core/component/dex/src/component/action_handler/swap.rs
  crates/core/component/dex/src/component/chandelier.rs
  crates/core/component/dex/src/component/circuit_breaker/mod.rs
  crates/core/component/dex/src/component/circuit_breaker/value.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/flow.rs
  crates/core/component/dex/src/component/mod.rs
  crates/core/component/dex/src/component/router/route_and_fill.rs
  crates/core/component/dex/src/component/router/tests.rs
  crates/core/component/dex/src/component/swap_manager.rs
  crates/core/component/dex/src/component/tests.rs
  crates/core/component/fee/Cargo.toml
  crates/core/component/fee/src/component.rs
  crates/core/component/fee/src/component/fee_pay.rs
  crates/core/component/fee/src/component/view.rs
  crates/core/component/fee/src/gas.rs
  crates/core/component/fee/src/state_key.rs
  crates/proto/src/gen/penumbra.core.component.fee.v1.rs
  crates/proto/src/gen/penumbra.core.component.fee.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/fee/v1/fee.proto
Labels: consensus-breaking, protobuf-changes, A-dex, A-fees

#4661 feat(crypto): add phase 2 outputs from ceremony
  crates/crypto/proof-params/src/gen/convert_id.rs
  crates/crypto/proof-params/src/gen/convert_pk.bin
  crates/crypto/proof-params/src/gen/convert_vk.param
  crates/crypto/proof-params/src/gen/delegator_vote_id.rs
  crates/crypto/proof-params/src/gen/delegator_vote_pk.bin
  crates/crypto/proof-params/src/gen/delegator_vote_vk.param
  crates/crypto/proof-params/src/gen/nullifier_derivation_id.rs
  crates/crypto/proof-params/src/gen/nullifier_derivation_pk.bin
  crates/crypto/proof-params/src/gen/nullifier_derivation_vk.param
  crates/crypto/proof-params/src/gen/output_id.rs
  crates/crypto/proof-params/src/gen/output_pk.bin
  crates/crypto/proof-params/src/gen/output_vk.param
  crates/crypto/proof-params/src/gen/spend_id.rs
  crates/crypto/proof-params/src/gen/spend_pk.bin
  crates/crypto/proof-params/src/gen/spend_vk.param
  crates/crypto/proof-params/src/gen/swap_id.rs
  crates/crypto/proof-params/src/gen/swap_pk.bin
  crates/crypto/proof-params/src/gen/swap_vk.param
  crates/crypto/proof-params/src/gen/swapclaim_id.rs
  crates/crypto/proof-params/src/gen/swapclaim_pk.bin
  crates/crypto/proof-params/src/gen/swapclaim_vk.param
Labels: consensus-breaking

#4664 app: make prepare proposal more robust to comet misconfiguration
  crates/core/app/src/app/mod.rs
Labels: A-node

#4666 cp: add `initial_balance` to content message
  crates/core/app/tests/app_can_disable_community_pool_spends.rs
  crates/core/app/tests/app_can_propose_community_pool_spends.rs
  crates/core/component/community-pool/src/component.rs
  crates/core/component/community-pool/src/component/action_handler/community_pool_deposit.rs
  crates/core/component/community-pool/src/component/view.rs
  crates/core/component/community-pool/src/genesis.rs
  crates/core/component/funding/src/component.rs
  crates/proto/src/gen/penumbra.core.component.community_pool.v1.rs
  crates/proto/src/gen/penumbra.core.component.community_pool.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/community_pool/v1/community_pool.proto
Labels: A-node

#4676 chore(pd): 🧹 tidy cli options for consistent whitespace
  crates/bin/pd/src/cli.rs
Labels: A-node

#4683 app: change max tx bytes constant to `96KB`
  crates/core/app/src/app/mod.rs
  testnets/cometbft_config_template.toml
Labels: A-node, consensus-breaking
