Repository penumbra-zone/penumbra, pull requests merged in 2024-07, with the labels that each got.

#4687 Use raw amount for staking issuance parameter
  crates/core/component/distributions/src/component.rs
  crates/core/component/distributions/src/params.rs
Labels: consensus-breaking

#4697 app(rpc): expose simtrade service by default
  crates/bin/pd/src/cli.rs
  crates/core/app/src/rpc.rs
Labels: A-node, A-dex

#4762 Fix: index events according to their local row id
  crates/util/cometindex/src/indexer.rs
Labels: C-bug

#4766 Bug: correctly handle denoms with `/` in pcli tx lp
  crates/core/component/dex/src/lp/order.rs
Labels: C-bug
