Repository penumbra-zone/penumbra, pull requests merged in 2024-05, with the labels that each got.

#4287 Add test for and fix arbitrage swap execution output amount
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/migrate/testnet74.rs
  crates/core/component/dex/src/component/arb.rs
  crates/core/component/dex/src/component/tests.rs
Labels: consensus-breaking, A-dex, state-breaking

#4295 auction: add views to the `ActionView` definition
  crates/core/asset/src/asset/cache.rs
  crates/core/component/auction/src/auction/dutch/actions/mod.rs
  crates/core/component/auction/src/auction/dutch/actions/schedule_view.rs
  crates/core/component/auction/src/auction/dutch/actions/view.rs
  crates/core/component/auction/src/auction/dutch/actions/withdraw_view.rs
  crates/core/transaction/src/action.rs
  crates/core/transaction/src/is_action.rs
  crates/core/transaction/src/view/action_view.rs
  crates/proto/src/gen/penumbra.core.component.auction.v1alpha1.rs
  crates/proto/src/gen/penumbra.core.transaction.v1.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  crates/view/src/service.rs
  proto/penumbra/penumbra/core/component/auction/v1alpha1/auction.proto
  proto/penumbra/penumbra/core/transaction/v1/transaction.proto
  proto/penumbra/penumbra/custody/threshold/v1/threshold.proto
  proto/penumbra/penumbra/custody/v1/custody.proto
Labels: protobuf-breaking-changes, A-auction

#4298 docs: add security email info to readme
  README.md
Labels: A-docs

#4315 Add stateful checks for chain ID and expiry height
  crates/core/app/src/action_handler/transaction.rs
  crates/core/app/src/action_handler/transaction/stateful.rs
  crates/core/app/src/genesis.rs
  crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs
  crates/core/app/tests/app_can_deposit_into_community_pool.rs
  crates/core/app/tests/app_can_disable_community_pool_spends.rs
  crates/core/app/tests/app_can_propose_community_pool_spends.rs
  crates/core/app/tests/app_can_spend_notes_and_detect_outputs.rs
  crates/core/app/tests/app_can_undelegate_from_a_validator.rs
  crates/core/app/tests/app_rejects_validator_definitions_with_invalid_auth_sigs.rs
  crates/core/app/tests/app_tracks_uptime_for_genesis_validator_missing_blocks.rs
  crates/core/app/tests/app_tracks_uptime_for_genesis_validator_signing_blocks.rs
  crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs
  crates/core/app/tests/mock_consensus_can_define_a_genesis_validator.rs
  crates/core/app/tests/mock_consensus_can_send_a_sequence_of_empty_blocks.rs
Labels: security, consensus-breaking, _P-critical

#4324 feat(tests): faster smokes via process-compose
  .github/workflows/smoke.yml
  crates/bin/pcli/tests/network_integration.rs
  deployments/compose/process-compose-smoke-test.yml
  deployments/scripts/smoke-test.sh
  docs/guide/src/dev/devnet-quickstart.md
  justfile
Labels: A-CI/CD, C-chore

#3467 refactor(transaction): Implement canonical ordering in `TransactionPlan`
  crates/bin/pcli/tests/network_integration.rs
  crates/core/transaction/src/action.rs
  crates/core/transaction/src/plan.rs
  crates/core/transaction/src/plan/action.rs
  crates/core/transaction/src/plan/build.rs
  crates/view/src/planner/action_list.rs
Labels: A-client, C-design

#4327 fix(metrics): validator missed blocks, inc -> set
  crates/core/component/stake/src/component/validator_handler/uptime_tracker.rs
Labels: C-bug, A-telemetry

#4317 app: fold ibc stateful/historical check into their AHs
  crates/core/app/src/action_handler/actions.rs
  crates/core/component/ibc/src/component/action_handler/ibc_action.rs
  crates/core/component/ibc/src/component/client.rs
  crates/core/component/shielded-pool/src/component/action_handler/ics20_withdrawal.rs
Labels: A-IBC

#4338 pd(migrate): add auction parameters to chain state for `Testnet74`
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/migrate/testnet74.rs
Labels: migration, A-auction

#4339 pd: improve migration UX
  crates/bin/pd/src/cli.rs
  crates/bin/pd/src/main.rs
  crates/bin/pd/src/migrate.rs
  docs/guide/src/node/pd/chain-upgrade.md
  docs/guide/src/upgrade_genesis_time_70_71.md
  docs/guide/src/upgrade_genesis_time_71_72.md
Labels: A-node, C-enhancement

#4349 view: 👀 introduce more tracing instrumentation
  Cargo.lock
  crates/view/Cargo.toml
  crates/view/src/service.rs
  crates/view/src/storage.rs
  crates/view/src/worker.rs
Labels: A-node, C-enhancement, A-telemetry

#4351 auction(rpc): support `grpc-web` in the auction query service
  crates/core/app/src/rpc.rs
Labels: C-bug, A-auction

#4343 Add an encrypted config option to pcli
  Cargo.lock
  crates/bin/pcli/src/command/init.rs
  crates/bin/pcli/src/command/threshold.rs
  crates/bin/pcli/src/config.rs
  crates/bin/pcli/src/opt.rs
  crates/bin/pcli/src/terminal.rs
  crates/custody/Cargo.toml
  crates/custody/src/encrypted.rs
  crates/custody/src/lib.rs
  crates/custody/src/terminal.rs
  crates/custody/src/threshold.rs
  crates/custody/src/threshold/sign.rs
  docs/guide/src/pcli/wallet.md
  docs/guide/src/pcli/wallet/softkms.md
  docs/guide/src/pcli/wallet/threshold.md
Labels: A-client, C-enhancement

#4354 chore(flake): 🥐 update lockfile
  flake.lock
Labels: A-tooling, C-chore

#4353 auction: define and record events
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/core/component/auction/src/component/action_handler/dutch/end.rs
  crates/core/component/auction/src/component/dutch_auction.rs
  crates/core/component/auction/src/event.rs
  crates/core/component/auction/src/lib.rs
  crates/proto/src/gen/penumbra.core.component.auction.v1alpha1.rs
  crates/proto/src/gen/penumbra.core.component.auction.v1alpha1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/auction/v1alpha1/auction.proto
Labels: protobuf-changes, A-auction

#4357 chore(pcli): 🧹 tidy entrypoint imports
  crates/bin/pcli/src/main.rs
Labels: A-client, C-chore

#4361 Better handle regex in `pcli query watch`
  crates/cnidarium/src/rpc.rs
Labels: A-client

#4363 auction(vcb): add a value circuit breaker
  crates/core/component/auction/src/component/action_handler/dutch/schedule.rs
  crates/core/component/auction/src/component/action_handler/dutch/withdraw.rs
  crates/core/component/auction/src/component/auction.rs
  crates/core/component/auction/src/component/dutch_auction.rs
  crates/core/component/auction/src/component/mod.rs
  crates/core/component/auction/src/event.rs
  crates/core/component/auction/src/state_key.rs
  crates/proto/src/gen/penumbra.core.component.auction.v1alpha1.rs
  crates/proto/src/gen/penumbra.core.component.auction.v1alpha1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/auction/v1alpha1/auction.proto
Labels: consensus-breaking, A-dex, A-auction

#4291 Include`DelegatorVoteView` as an `ActionView` with `Visible` and `Opaque` Variants
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/proto/src/gen/penumbra.core.transaction.v1.rs
  crates/proto/src/gen/penumbra.core.transaction.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/transaction/v1/transaction.proto
Labels: protobuf-changes

#4375 chore: prepare testnet 75
  COMPATIBILITY.md
  crates/core/app/src/lib.rs
  testnets/071-deimos-6/allocations.csv
  testnets/071-deimos-6/validators.json
  testnets/072-deimos-6/allocations.csv
  testnets/072-deimos-6/validators.json
  testnets/073-deimos-7/allocations.csv
  testnets/073-deimos-7/validators.json
  testnets/073-deimos-8/allocations.csv
  testnets/073-deimos-8/validators.json
Labels: C-chore

#4382 ci: 🩹 add missing `"` to pid expansion
  deployments/scripts/smoke-summoner.sh
Labels: C-bug, A-CI/CD

#4378 misc: 🩹 apply some review suggestions
  crates/bin/pcli/Cargo.toml
  crates/bin/pcli/src/command/tx/auction/dutch.rs
  crates/core/component/auction/src/component/rpc.rs
Labels: E-easy, C-chore, A-auction

#4292 dex: Extend arbitrage routing
  crates/core/component/dex/src/component/action_handler/swap.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/position_manager.rs
  crates/core/component/dex/src/component/router/tests.rs
  crates/core/component/dex/src/state_key.rs
Labels: consensus-breaking, A-dex

#4387 ci: add `penumbra-mock-*` to rustdoc build list
  deployments/scripts/rust-docs
Labels: A-CI/CD

#4390 docs: add upgrade planning checklist
  .github/ISSUE_TEMPLATE/upgrade_testnet.md
Labels: C-enhancement, A-docs, A-upgrades

#4415 ci: fix rust-docs build
  .gitignore
  Cargo.lock
  docs/rustdoc/index.html
Labels: A-CI/CD, C-chore

#4413 app: switch halt counter with halt bit
  crates/bin/pd/src/cli.rs
  crates/bin/pd/src/main.rs
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/migrate/reset_halt_bit.rs
  crates/bin/pd/src/migrate/simple.rs
  crates/bin/pd/src/migrate/testnet72.rs
  crates/bin/pd/src/migrate/testnet74.rs
  crates/core/app/src/app/mod.rs
  crates/core/app/src/app/state_key.rs
  crates/core/component/governance/src/component/view.rs
  crates/core/component/governance/src/state_key.rs
  crates/proto/src/state/read.rs
  crates/proto/src/state/write.rs
Labels: A-governance, consensus-breaking, state-breaking

#4424 tonic: 🍸 patch tonic dependencies
  Cargo.lock
  Cargo.toml
Labels: A-tooling, C-chore

#4394 auction: credit VCB when ending an auction
  crates/bin/pd/src/main.rs
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/migrate/testnet76.rs
  crates/cnidarium/src/lib.rs
  crates/cnidarium/src/snapshot.rs
  crates/cnidarium/src/storage.rs
  crates/cnidarium/src/write_batch.rs
  crates/core/app/Cargo.toml
  crates/core/app/tests/app_reproduce_testnet_75_vcb_close.rs
  crates/core/app/tests/common/mod.rs
  crates/core/component/auction/src/component/action_handler/dutch/end.rs
  crates/core/component/auction/src/component/auction.rs
  crates/core/component/auction/src/component/auction_store.rs
  crates/core/component/auction/src/component/dutch_auction.rs
  crates/core/component/auction/src/component/mod.rs
  crates/core/component/auction/src/component/rpc.rs
  crates/core/component/auction/src/state_key.rs
  crates/core/component/dex/src/component/circuit_breaker/value.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/position_manager.rs
  crates/core/component/dex/src/component/position_manager/base_liquidity_index.rs
  crates/core/component/dex/src/component/position_manager/inventory_index.rs
  crates/core/component/dex/src/component/router/path.rs
  crates/core/component/dex/src/component/router/path_search.rs
  crates/test/tracing-subscriber/src/lib.rs
Labels: C-bug, consensus-breaking, state-breaking, migration, A-auction

#4137 FMD Parameter Selection Breaking Changes
  Cargo.lock
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/migrate/testnet76.rs
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/core/app/Cargo.toml
  crates/core/app/src/action_handler/transaction.rs
  crates/core/app/src/action_handler/transaction/stateful.rs
  crates/core/app/src/params/change.rs
  crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs
  crates/core/app/tests/app_can_deposit_into_community_pool.rs
  crates/core/app/tests/app_can_disable_community_pool_spends.rs
  crates/core/app/tests/app_can_propose_community_pool_spends.rs
  crates/core/app/tests/app_can_spend_notes_and_detect_outputs.rs
  crates/core/app/tests/app_can_undelegate_from_a_validator.rs
  crates/core/app/tests/app_rejects_validator_definitions_with_invalid_auth_sigs.rs
  crates/core/app/tests/app_reproduce_testnet_75_vcb_close.rs
  crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs
  crates/core/component/shielded-pool/src/component.rs
  crates/core/component/shielded-pool/src/component/fmd.rs
  crates/core/component/shielded-pool/src/component/shielded_pool.rs
  crates/core/component/shielded-pool/src/fmd.rs
  crates/core/component/shielded-pool/src/fmd/state_key.rs
  crates/core/component/shielded-pool/src/params.rs
  crates/core/transaction/src/action_list.rs
  crates/core/transaction/src/plan.rs
  crates/core/transaction/src/plan/clue.rs
  crates/crypto/decaf377-fmd/benches/fmd.rs
  crates/crypto/decaf377-fmd/src/clue.rs
  crates/crypto/decaf377-fmd/src/clue_key.rs
  crates/crypto/decaf377-fmd/src/detection.rs
  crates/crypto/decaf377-fmd/src/error.rs
  crates/crypto/decaf377-fmd/src/hash.rs
  crates/crypto/decaf377-fmd/src/lib.rs
  crates/crypto/decaf377-fmd/src/precision.rs
  crates/crypto/decaf377-fmd/tests/fmd.rs
  crates/proto/src/gen/penumbra.core.component.shielded_pool.v1.rs
  crates/proto/src/gen/penumbra.core.component.shielded_pool.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  crates/proto/src/protobuf.rs
  proto/penumbra/penumbra/core/component/shielded_pool/v1/shielded_pool.proto
Labels: A-shielded-crypto, consensus-breaking, state-breaking, migration

#4428 dex: deduct arb surplus from component VCB
  crates/core/component/dex/src/component/arb.rs
  crates/core/component/dex/src/component/circuit_breaker/execution.rs
  crates/core/component/dex/src/component/circuit_breaker/mod.rs
  crates/core/component/dex/src/component/circuit_breaker/value.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/mod.rs
Labels: consensus-breaking, A-dex, state-breaking

#4429 ci: faster cargo check features
  .github/workflows/rust.yml
Labels: A-CI/CD

#4386 ibc: audit fixes
  crates/core/component/ibc/src/component/msg_handler/channel_open_ack.rs
  crates/core/component/ibc/src/component/msg_handler/connection_open_ack.rs
  crates/core/component/ibc/src/component/msg_handler/timeout.rs
  crates/core/component/ibc/src/component/msg_handler/upgrade_client.rs
  crates/core/component/ibc/src/component/proof_verification.rs
Labels: A-IBC, security, consensus-breaking, zellic-ibc-remediated

#4434 view: 📫 do not thrash `error_slot` mutex
  crates/view/src/service.rs
Labels: A-client, C-enhancement

#4439 pcli: improve error message for delegation failure to suggest pcli tx sweep
  crates/bin/pcli/src/command/tx.rs
Labels: A-client

#4440 governance: lower emergency vote threshold to 1/3
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/core/component/governance/src/action_handler/validator_vote.rs
  crates/core/component/governance/src/proposal.rs
  crates/core/component/governance/src/tally.rs
  crates/proto/src/gen/penumbra.core.component.governance.v1.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  docs/guide/src/pcli/governance.md
  docs/protocol/src/concepts/governance.md
  docs/protocol/src/governance.md
  proto/penumbra/penumbra/core/component/governance/v1/governance.proto
Labels: consensus-breaking

#4445 pd(migrate): set halt flag to false
  crates/bin/pd/src/migrate/testnet76.rs
Labels: migration

#4436 pd: refuse to bootstrap services if the app is not ready
  crates/bin/pd/src/main.rs
  crates/core/app/src/app/mod.rs
  crates/core/app/src/server.rs
  crates/core/app/src/server/consensus.rs
  crates/core/app/src/server/mempool.rs
  crates/core/app/tests/common/temp_storage_ext.rs
Labels: A-node

#4451 docs(guide): update version to v0.75.1
  docs/guide/src/penumbra_version.md
Labels: A-docs, C-chore

#4461 Change "unmissed signing" to "successful signing" in console output
  crates/bin/pcli/src/command/query/validator.rs
Labels: A-client

#4460 app: 👐 `rpc::router(..)` accepts a `TendermintProxyService`
  crates/bin/pd/src/main.rs
  crates/core/app/src/rpc.rs
Labels: A-node, A-testing, A-mock-consensus, C-refactor

#4442 Correct display of downtime in `pcli validator query uptime`
  crates/bin/pcli/src/command/query/validator.rs
Labels: A-client, C-bug, _P-low

#4466 dex: add duration metric for SimulateTrade RPC (#4454)
  crates/core/component/dex/src/component/action_handler/swap.rs
  crates/core/component/dex/src/component/metrics.rs
  crates/core/component/dex/src/component/rpc.rs
Labels: A-telemetry, A-dex

#4398 dex: Generate candlestick data and provide RPCs for access
  Cargo.lock
  crates/core/asset/src/asset/id.rs
  crates/core/component/dex/Cargo.toml
  crates/core/component/dex/src/component/candlestick/candlestick.rs
  crates/core/component/dex/src/component/candlestick/chandelier.rs
  crates/core/component/dex/src/component/candlestick/mod.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/mod.rs
  crates/core/component/dex/src/component/position_manager.rs
  crates/core/component/dex/src/component/router/route_and_fill.rs
  crates/core/component/dex/src/component/rpc.rs
  crates/core/component/dex/src/state_key.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.rs
  crates/proto/src/gen/penumbra.core.component.dex.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/dex/v1/dex.proto
Labels: C-enhancement, protobuf-changes, A-dex

#4479 Fix alignment for validator uptime printout
  crates/bin/pcli/src/command/query/validator.rs
Labels: A-client, C-refactor

#4469 transaction: 🧁 `TransactionPlan::with_populated_detection_data()`
  crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs
  crates/core/app/tests/app_can_disable_community_pool_spends.rs
  crates/core/app/tests/app_can_spend_notes_and_detect_outputs.rs
  crates/core/app/tests/app_can_undelegate_from_a_validator.rs
  crates/core/app/tests/app_reproduce_testnet_75_vcb_close.rs
  crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs
  crates/core/transaction/src/plan.rs
Labels: _P-low, A-testing, C-refactor

#4470 mock-consensus: ⭐ assert that `TestNode<C>` is `Send + Sync`
  crates/test/mock-consensus/src/lib.rs
Labels: _P-low, A-mock-consensus, C-refactor

#4474 cnidarium(watch): always check that the channel is open
  crates/cnidarium/src/rpc.rs
Labels: A-node

#4385 pcli: auction end-all, withdraw-all
  crates/bin/pcli/src/command/query/auction.rs
  crates/bin/pcli/src/command/tx/auction/dutch.rs
  crates/bin/pcli/src/command/view/auction.rs
  crates/view/src/client.rs
  crates/view/src/planner.rs
  crates/view/src/service.rs
  crates/view/src/storage.rs
Labels: A-client, A-auction

#4498 crypto: used fixed nonce for swap symmetric encryption
  crates/core/component/dex/src/swap/ciphertext.rs
  crates/core/keys/src/symmetric.rs
  crates/core/transaction/src/is_action.rs
Labels: ecc-component-remediated

#4496 chore: 🪨 improve incremental builds by linking to rocksdb
  docs/guide/src/dev/build.md
  flake.nix
Labels: A-tooling, A-docs

#4477 ci: automate chain upgrades on k8s deployments
  deployments/charts/penumbra-network/values.yaml
  deployments/helmfile.d/penumbra-devnet.yaml
  deployments/scripts/k8s-deploy-point-release
  deployments/scripts/k8s-disable-maintenance-mode
  deployments/scripts/k8s-enable-maintenance-mode
  deployments/scripts/k8s-perform-chain-upgrade-via-pd-migrate
Labels: C-enhancement, A-CI/CD, A-upgrades

#4505 auction: disallow new auctions if the dex is disabled
  crates/core/component/auction/src/component/action_handler/dutch/schedule.rs
Labels: consensus-breaking, A-dex, A-auction
