Repository penumbra-zone/penumbra, pull requests merged in 2024-02, with the labels that each got.

#3723 sct(component): implement `Component` trait and split modules
  Cargo.lock
  crates/bin/pcli/src/command/query/shielded_pool.rs
  crates/bin/pd/src/migrate.rs
  crates/core/app/src/action_handler/actions/submit.rs
  crates/core/app/src/action_handler/transaction.rs
  crates/core/app/src/action_handler/transaction/stateful.rs
  crates/core/app/src/app/mod.rs
  crates/core/app/src/community_pool_ext.rs
  crates/core/app/src/mock_client.rs
  crates/core/app/src/penumbra_host_chain.rs
  crates/core/app/src/tests/spend.rs
  crates/core/app/src/tests/swap_and_swap_claim.rs
  crates/core/component/compact-block/src/component/manager.rs
  crates/core/component/compact-block/src/component/rpc.rs
  crates/core/component/dex/src/component/action_handler/swap.rs
  crates/core/component/dex/src/component/action_handler/swap_claim.rs
  crates/core/component/dex/src/component/arb.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/swap_manager.rs
  crates/core/component/dex/src/component/tests.rs
  crates/core/component/distributions/src/component.rs
  crates/core/component/governance/src/component.rs
  crates/core/component/governance/src/component/view.rs
  crates/core/component/ibc/src/component/client.rs
  crates/core/component/sct/Cargo.toml
  crates/core/component/sct/src/component.rs
  crates/core/component/sct/src/component/clock.rs
  crates/core/component/sct/src/component/mod.rs
  crates/core/component/sct/src/component/rpc.rs
  crates/core/component/sct/src/component/sct.rs
  crates/core/component/sct/src/component/source.rs
  crates/core/component/sct/src/component/tree.rs
  crates/core/component/sct/src/component/view.rs
  crates/core/component/sct/src/state_key.rs
  crates/core/component/shielded-pool/src/component/action_handler/output.rs
  crates/core/component/shielded-pool/src/component/action_handler/spend.rs
  crates/core/component/shielded-pool/src/component/note_manager.rs
  crates/core/component/shielded-pool/src/component/shielded_pool.rs
  crates/core/component/stake/src/action_handler/undelegate_claim.rs
  crates/core/component/stake/src/action_handler/validator_definition.rs
  crates/core/component/stake/src/component.rs
  crates/view/src/worker.rs
Labels: A-node

#3745 penumbra: use `metrics@0.22`
  Cargo.lock
  crates/bin/pclientd/Cargo.toml
  crates/bin/pd/Cargo.toml
  crates/bin/pd/src/mempool.rs
  crates/bin/pd/src/metrics.rs
  crates/cnidarium/Cargo.toml
  crates/cnidarium/src/metrics.rs
  crates/cnidarium/src/snapshot.rs
  crates/core/app/Cargo.toml
  crates/core/component/community-pool/Cargo.toml
  crates/core/component/compact-block/Cargo.toml
  crates/core/component/compact-block/src/component/metrics.rs
  crates/core/component/compact-block/src/component/rpc.rs
  crates/core/component/dex/Cargo.toml
  crates/core/component/dex/src/component/action_handler/swap.rs
  crates/core/component/dex/src/component/arb.rs
  crates/core/component/dex/src/component/dex.rs
  crates/core/component/dex/src/component/metrics.rs
  crates/core/component/dex/src/component/router/fill_route.rs
  crates/core/component/dex/src/component/router/path_search.rs
  crates/core/component/fee/Cargo.toml
  crates/core/component/governance/Cargo.toml
  crates/core/component/ibc/Cargo.toml
  crates/core/component/sct/Cargo.toml
  crates/core/component/shielded-pool/Cargo.toml
  crates/core/component/stake/Cargo.toml
  crates/core/component/stake/src/component.rs
  crates/core/component/stake/src/component/metrics.rs
  crates/util/tendermint-proxy/Cargo.toml
  crates/view/Cargo.toml
Labels: A-telemetry

#3749 📌 fix(ci): pin nightly toolchain
  .github/workflows/rust.yml
  deployments/scripts/rust-docs
  docs/rustdoc/index.html
Labels: A-CI/CD, C-chore

#3752 Emit ABCI events from governance-related actions
  crates/cnidarium/src/gen/proto_descriptor.bin.no_lfs
  crates/core/app/src/action_handler/actions/submit.rs
  crates/core/component/governance/src/action_handler/delegator_vote.rs
  crates/core/component/governance/src/action_handler/deposit_claim.rs
  crates/core/component/governance/src/action_handler/validator_vote.rs
  crates/core/component/governance/src/action_handler/withdraw.rs
  crates/core/component/governance/src/component.rs
  crates/core/component/governance/src/delegator_vote/action.rs
  crates/core/component/governance/src/delegator_vote/proof.rs
  crates/core/component/governance/src/event.rs
  crates/core/component/governance/src/lib.rs
  crates/core/component/governance/src/proposal_deposit_claim/action.rs
  crates/core/component/governance/src/proposal_state.rs
  crates/proto/src/gen/penumbra.core.component.governance.v1alpha1.rs
  crates/proto/src/gen/penumbra.core.component.governance.v1alpha1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/go/gen/penumbra/core/component/governance/v1alpha1/governance.pb.go
  proto/penumbra/penumbra/core/component/governance/v1alpha1/governance.proto
Labels: A-governance

#3748 Make all crates use workspace dependencies when shared
  Cargo.lock
  Cargo.toml
  crates/bench/Cargo.toml
  crates/bin/pcli/Cargo.toml
  crates/bin/pclientd/Cargo.toml
  crates/bin/pclientd/tests/network_integration.rs
  crates/bin/pd/Cargo.toml
  crates/cnidarium-component/Cargo.toml
  crates/cnidarium/Cargo.toml
  crates/core/app/Cargo.toml
  crates/core/asset/Cargo.toml
  crates/core/component/community-pool/Cargo.toml
  crates/core/component/compact-block/Cargo.toml
  crates/core/component/dex/Cargo.toml
  crates/core/component/distributions/Cargo.toml
  crates/core/component/fee/Cargo.toml
  crates/core/component/funding/Cargo.toml
  crates/core/component/governance/Cargo.toml
  crates/core/component/ibc/Cargo.toml
  crates/core/component/ibc/src/component/client.rs
  crates/core/component/sct/Cargo.toml
  crates/core/component/shielded-pool/Cargo.toml
  crates/core/component/shielded-pool/src/convert.rs
  crates/core/component/shielded-pool/src/nullifier_derivation.rs
  crates/core/component/shielded-pool/src/output/proof.rs
  crates/core/component/shielded-pool/src/spend/proof.rs
  crates/core/component/stake/Cargo.toml
  crates/core/component/stake/src/undelegate_claim/proof.rs
  crates/core/keys/Cargo.toml
  crates/core/num/Cargo.toml
  crates/core/transaction/Cargo.toml
  crates/core/txhash/Cargo.toml
  crates/crypto/decaf377-fmd/Cargo.toml
  crates/crypto/decaf377-frost/Cargo.toml
  crates/crypto/decaf377-ka/Cargo.toml
  crates/crypto/eddy/Cargo.toml
  crates/crypto/proof-params/Cargo.toml
  crates/crypto/proof-setup/Cargo.toml
  crates/crypto/tct/Cargo.toml
  crates/custody/Cargo.toml
  crates/custody/src/policy.rs
  crates/misc/measure/Cargo.toml
  crates/misc/tct-visualize/Cargo.toml
  crates/proto/Cargo.toml
  crates/test/tct-property-test/Cargo.toml
  crates/util/auto-https/Cargo.toml
  crates/util/tendermint-proxy/Cargo.toml
  crates/util/tower-trace/Cargo.toml
  crates/view/Cargo.toml
  crates/wallet/Cargo.toml
  crates/wasm/Cargo.toml
  tools/parameter-setup/Cargo.toml
  tools/summonerd/Cargo.toml
Labels: E-medium, A-tooling, C-chore

#3778 ci: fix yaml typo in testnet manifest
  deployments/helmfile.d/penumbra-testnet.yaml
Labels: A-CI/CD

#3770 staking: add missing effect for `Defined <> Inactive`
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
Labels: A-staking, C-bug

#3803 staking: use validator exchange rate to compute rewards
  crates/core/component/funding/src/component.rs
  crates/core/component/stake/src/component/epoch_handler.rs
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
  crates/core/component/stake/src/funding_stream.rs
  crates/core/component/stake/src/state_key.rs
Labels: A-staking, C-bug

#3801 penumbra: fix metrics by bumping helper crates
  Cargo.lock
  Cargo.toml
  crates/bin/pd/Cargo.toml
Labels: C-bug, A-telemetry

#3768 staking: add limit on number of validator funding streams
  crates/core/component/stake/src/component/action_handler/validator_definition.rs
  crates/core/component/stake/src/funding_stream.rs
Labels: A-staking, C-enhancement

#3810 tests: ✨ provide app state in genesis request
  Cargo.lock
  crates/core/app/tests/common/mod.rs
  crates/core/app/tests/mock_consensus.rs
  crates/test/mock-consensus/Cargo.toml
  crates/test/mock-consensus/src/builder.rs
  crates/test/mock-consensus/src/builder/init_chain.rs
  crates/test/mock-consensus/src/lib.rs
Labels: A-mock-consensus

#3823 docs: update compatibility matrix
  COMPATIBILITY.md
Labels: A-docs

#3772 refactor(wasm): remove wasm crate from monorepo
  .github/workflows/npm.yml
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  crates/wasm/.gitignore
  crates/wasm/Cargo.toml
  crates/wasm/README.md
  crates/wasm/publish/.prettierrc
  crates/wasm/publish/package-lock.json
  crates/wasm/publish/package.json
  crates/wasm/publish/run.ts
  crates/wasm/publish/tsconfig.json
  crates/wasm/src/build.rs
  crates/wasm/src/dex.rs
  crates/wasm/src/error.rs
  crates/wasm/src/keys.rs
  crates/wasm/src/lib.rs
  crates/wasm/src/note_record.rs
  crates/wasm/src/planner.rs
  crates/wasm/src/storage.rs
  crates/wasm/src/swap_record.rs
  crates/wasm/src/tx.rs
  crates/wasm/src/utils.rs
  crates/wasm/src/view_server.rs
  crates/wasm/src/wasm_planner.rs
  crates/wasm/tests/test_build.rs
  crates/wasm/tests/test_deserialize.rs
  crates/wasm/tests/test_keys.rs
  deployments/scripts/rust-docs
Labels: A-wasm

#3822 mock-consensus: 🚀 test node can send an empty block
  crates/core/app/tests/mock_consensus.rs
  crates/test/mock-consensus/src/block.rs
  crates/test/mock-consensus/src/lib.rs
  crates/test/mock-consensus/src/send_block.rs
Labels: C-enhancement, A-mock-consensus, _P-high

#3820 staking(undelegate_claim): fix unbonding check condition
  crates/core/component/stake/src/component/action_handler/undelegate_claim.rs
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
  deployments/scripts/smoke-test.sh
Labels: consensus-breaking

#3783 Strip ICS20 prefix from beginning of packet data denoms only
  crates/core/component/shielded-pool/src/component/transfer.rs
Labels: zellic-component-remediated

#3785 Use checked math for ICS20 withdrawal addition
  crates/core/component/shielded-pool/src/component/transfer.rs
Labels: zellic-component-remediated

#3829 dex: 🏒 `SwapClaimProof::verify` is fallible
  Cargo.lock
  Cargo.toml
  crates/core/component/dex/Cargo.toml
  crates/core/component/dex/src/swap_claim/proof.rs
  crates/test/mock-consensus/Cargo.toml
Labels: A-node, security, zellic-component-remediated, _P-high

#3835 dependencies: 🧹 sort `Cargo.toml` dependencies
  crates/bench/Cargo.toml
  crates/bin/pcli/Cargo.toml
  crates/bin/pclientd/Cargo.toml
  crates/cnidarium-component/Cargo.toml
  crates/cnidarium/Cargo.toml
  crates/core/app/Cargo.toml
  crates/core/asset/Cargo.toml
  crates/core/component/community-pool/Cargo.toml
  crates/core/component/compact-block/Cargo.toml
  crates/core/component/dex/Cargo.toml
  crates/core/component/distributions/Cargo.toml
  crates/core/component/fee/Cargo.toml
  crates/core/component/funding/Cargo.toml
  crates/core/component/governance/Cargo.toml
  crates/core/component/ibc/Cargo.toml
  crates/core/component/sct/Cargo.toml
  crates/core/component/shielded-pool/Cargo.toml
  crates/core/component/stake/Cargo.toml
  crates/core/keys/Cargo.toml
  crates/core/num/Cargo.toml
  crates/core/transaction/Cargo.toml
  crates/core/txhash/Cargo.toml
  crates/crypto/decaf377-fmd/Cargo.toml
  crates/crypto/decaf377-ka/Cargo.toml
  crates/crypto/eddy/Cargo.toml
  crates/crypto/proof-params/Cargo.toml
  crates/crypto/proof-setup/Cargo.toml
  crates/crypto/tct/Cargo.toml
  crates/custody/Cargo.toml
  crates/misc/measure/Cargo.toml
  crates/proto/Cargo.toml
  crates/test/tct-property-test/Cargo.toml
  crates/util/tendermint-proxy/Cargo.toml
  crates/view/Cargo.toml
  crates/wallet/Cargo.toml
  tools/proto-compiler/Cargo.toml
  tools/summonerd/Cargo.toml
Labels: A-tooling, C-chore

#3836 docs: stipulate support for precompiled binaries
  docs/guide/src/pcli/install.md
  docs/guide/src/pd/install.md
Labels: C-enhancement, A-docs

#3833 governance: 🎾 `DelegatorVoteProof::verify` is fallible
  Cargo.lock
  crates/core/component/governance/Cargo.toml
  crates/core/component/governance/src/delegator_vote/proof.rs
Labels: A-node, security, zellic-component-remediated, _P-high

#3834 shielded-pool: 🏊 `SpendProof::verify` is fallible
  Cargo.lock
  crates/core/component/shielded-pool/Cargo.toml
  crates/core/component/shielded-pool/src/spend/proof.rs
Labels: A-node, security, zellic-component-remediated, _P-high

#3840 mock-consensus: 💹 generated blocks' height increases
  crates/core/app/tests/mock_consensus.rs
  crates/test/mock-consensus/src/block.rs
  crates/test/mock-consensus/src/builder/init_chain.rs
  crates/test/mock-consensus/src/lib.rs
Labels: C-enhancement, A-mock-consensus

#3831 Fix delegation token regex to check boundaries
  crates/core/component/stake/src/delegation_token.rs
Labels: zellic-component-remediated

#3848 mock-consensus: 💇 use `evidence::List::default`
  crates/core/app/tests/mock_consensus.rs
  crates/test/mock-consensus/src/block.rs
Labels: A-mock-consensus

#3849 mock-consensus: 🙂 simplify test node startup
  Cargo.lock
  crates/core/app/Cargo.toml
  crates/core/app/src/server/consensus.rs
  crates/core/app/tests/common/mod.rs
  crates/core/app/tests/mock_consensus.rs
Labels: C-chore, A-mock-consensus

#3864 transaction: 🚪 reëxport `TransactionPlan`
  crates/bin/pcli/src/command/tx/proposal.rs
  crates/bin/pcli/src/network.rs
  crates/bin/pcli/src/terminal.rs
  crates/bin/pclientd/tests/network_integration.rs
  crates/core/app/src/action_handler/actions/submit.rs
  crates/core/transaction/src/lib.rs
  crates/core/transaction/src/plan/auth.rs
  crates/custody/src/policy.rs
  crates/custody/src/pre_auth.rs
  crates/custody/src/request.rs
  crates/custody/src/soft_kms.rs
  crates/custody/src/threshold.rs
  crates/custody/src/threshold/sign.rs
  crates/view/src/client.rs
  crates/view/src/service.rs
  crates/wallet/src/build.rs
  crates/wallet/src/plan.rs
Labels: C-chore, _P-low

#3870 fix(pd): re-add cors headers
  .github/workflows/smoke.yml
  crates/bin/pd/src/main.rs
  crates/bin/pd/tests/network_integration.rs
  deployments/scripts/smoke-test.sh
Labels: A-node, C-bug

#3828 staking: augment end-epoch validator set
  crates/core/app/src/app/mod.rs
  crates/core/component/funding/src/component.rs
  crates/core/component/stake/src/component/action_handler/delegate.rs
  crates/core/component/stake/src/component/epoch_handler.rs
  crates/core/component/stake/src/component/mod.rs
  crates/core/component/stake/src/component/stake.rs
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
  crates/core/component/stake/src/funding_stream.rs
  crates/core/component/stake/src/lib.rs
  crates/core/component/stake/src/rate.rs
  crates/core/component/stake/src/state_key.rs
Labels: A-staking, consensus-breaking

#3881 mock-consensus: 📵 raise default tracing log level in tests
  crates/core/app/tests/common/mod.rs
Labels: A-testing, A-mock-consensus

#3880 app: 🌸 add context messages to assorted errors
  crates/core/app/src/app/mod.rs
Labels: C-chore, A-telemetry

#3522 pd: allow bundling the web frontend into the fullnode
  .gitattributes
  Cargo.lock
  assets/minifront.zip
  assets/node-status.zip
  crates/bin/pd/Cargo.toml
  crates/bin/pd/src/lib.rs
  crates/bin/pd/src/main.rs
  crates/bin/pd/src/zipserve.rs
Labels: A-node, C-enhancement

#3877 staking: add a `min_validator_stake` first delegation requirement
  crates/core/component/stake/src/component/action_handler/delegate.rs
  crates/core/component/stake/src/component/action_handler/validator_definition.rs
  crates/core/component/stake/src/component/epoch_handler.rs
  crates/core/component/stake/src/component/stake.rs
  crates/core/component/stake/src/component/validator_handler/validator_manager.rs
  crates/core/component/stake/src/component/validator_handler/validator_store.rs
Labels: A-staking, consensus-breaking

#3892 chore: 📦 pre-release v0.68.0.alpha.1
  COMPATIBILITY.md
  Cargo.lock
  Cargo.toml
  docs/guide/src/penumbra_version.md
Labels: C-chore

#3895 staking: remove `component::FP_SCALING_FACTOR` dup
  COMPATIBILITY.md
  Cargo.lock
  Cargo.toml
  crates/core/component/stake/src/component/epoch_handler.rs
  crates/core/component/stake/src/component/mod.rs
  crates/core/component/stake/src/funding_stream.rs
  crates/core/component/stake/src/lib.rs
  crates/core/component/stake/src/rate.rs
  docs/guide/src/penumbra_version.md
Labels: A-wasm

#3891 app: 💸 a mock consensus spend is performed
  Cargo.lock
  crates/core/app/src/action_handler/transaction/stateful.rs
  crates/core/app/tests/mock_consensus.rs
  crates/core/app/tests/spend.rs
  crates/core/app/tests/swap_and_swap_claim.rs
  crates/core/transaction/src/memo.rs
  crates/test/mock-client/Cargo.toml
  crates/test/mock-client/src/lib.rs
  crates/test/mock-consensus/src/builder/init_chain.rs
  crates/test/mock-consensus/src/lib.rs
Labels: A-mock-consensus

#3900 app: 🤠 address warning
  crates/core/app/tests/spend.rs
Labels: C-chore, A-testing

#3903 Check value balance during IBC packet timeout
  crates/core/component/shielded-pool/src/component/transfer.rs
Labels: zellic-component-remediated
