Repository penumbra-zone/penumbra, pull requests merged in 2025-01, with the labels that each got.

#4981 Pindexer metrics fix
  crates/bin/pindexer/src/dex_ex/mod.rs
Labels: C-bug, A-indexing

#5000 proto(asset): add `coingecko_id` to `Metadata`
  crates/core/asset/src/asset/denom_metadata.rs
  crates/proto/src/gen/penumbra.core.asset.v1.rs
  crates/proto/src/gen/penumbra.core.asset.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/asset/v1/asset.proto
Labels: protobuf-changes

#5018 Add chain parameters for configuring LQT distributions
  crates/core/app/src/params/change.rs
  crates/core/component/distributions/src/params.rs
  crates/proto/src/gen/penumbra.core.component.distributions.v1.rs
  crates/proto/src/gen/penumbra.core.component.distributions.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/distributions/v1/distributions.proto
Labels: consensus-breaking

#5020 Implement parameters for liquidity tournament control (in funding)
  crates/core/app/src/params/change.rs
  crates/core/component/funding/src/component.rs
  crates/core/component/funding/src/params.rs
  crates/core/num/src/lib.rs
  crates/core/num/src/percentage/mod.rs
  crates/proto/src/gen/penumbra.core.component.funding.v1.rs
  crates/proto/src/gen/penumbra.core.component.funding.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/funding/v1/funding.proto
Labels: consensus-breaking

#5026 distributions: LQT pool budget
  crates/core/component/distributions/src/component.rs
  crates/core/component/distributions/src/component/state_key.rs
  crates/core/component/distributions/src/component/view.rs
Labels: consensus-breaking

#5030 dex: track outflows in position manager
  crates/core/component/dex/src/component/position_manager.rs
  crates/core/component/dex/src/component/position_manager/volume_tracker.rs
Labels: consensus-breaking, A-dex, state-breaking

#5027 Implement LQT Voting action, and stateless checks
  Cargo.lock
  crates/bin/pcli/src/transaction_view_ext.rs
  crates/core/app/src/action_handler/actions.rs
  crates/core/asset/src/asset/denom.rs
  crates/core/component/funding/Cargo.toml
  crates/core/component/funding/src/action_handler/liquidity_tournament/mod.rs
  crates/core/component/funding/src/action_handler/mod.rs
  crates/core/component/funding/src/lib.rs
  crates/core/component/funding/src/liquidity_tournament/action/mod.rs
  crates/core/component/funding/src/liquidity_tournament/mod.rs
  crates/core/component/funding/src/liquidity_tournament/proof/mod.rs
  crates/core/component/funding/src/liquidity_tournament/view/mod.rs
  crates/core/component/governance/src/delegator_vote/proof.rs
  crates/core/transaction/Cargo.toml
  crates/core/transaction/src/action.rs
  crates/core/transaction/src/gas.rs
  crates/core/transaction/src/is_action.rs
  crates/core/transaction/src/transaction.rs
  crates/core/transaction/src/view/action_view.rs
  crates/proto/src/gen/penumbra.core.component.funding.v1.rs
  crates/proto/src/gen/penumbra.core.component.funding.v1.serde.rs
  crates/proto/src/gen/penumbra.core.transaction.v1.rs
  crates/proto/src/gen/penumbra.core.transaction.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/funding/v1/funding.proto
  proto/penumbra/penumbra/core/transaction/v1/transaction.proto
Labels: consensus-breaking

#5034 funding: LQT nullifier set for epoch
  crates/core/app-tests/tests/spend.rs
  crates/core/component/funding/src/component.rs
  crates/core/component/funding/src/component/liquidity_tournament/mod.rs
  crates/core/component/funding/src/component/liquidity_tournament/nullifier/mod.rs
  crates/core/component/funding/src/component/state_key.rs
  crates/core/component/funding/src/component/view.rs
  crates/core/transaction/src/transaction.rs
  crates/core/txhash/src/context.rs
Labels: consensus-breaking

#5033 Implement check and execute for LQT votes
  crates/core/component/funding/Cargo.toml
  crates/core/component/funding/src/action_handler/liquidity_tournament/mod.rs
  crates/core/component/funding/src/component/liquidity_tournament/mod.rs
  crates/core/component/funding/src/component/liquidity_tournament/nullifier/mod.rs
  crates/core/component/funding/src/component/liquidity_tournament/votes/mod.rs
  crates/core/component/funding/src/component/state_key.rs
  crates/core/component/funding/src/liquidity_tournament/action/mod.rs
Labels: consensus-breaking

#5035 Implement "Bank" extension trait for liquidity tournament
  Cargo.lock
  crates/core/component/dex/src/component/position_manager.rs
  crates/core/component/funding/Cargo.toml
  crates/core/component/funding/src/component/liquidity_tournament/bank.rs
  crates/core/component/funding/src/component/liquidity_tournament/mod.rs
Labels: consensus-breaking
