Repository penumbra-zone/penumbra, pull requests merged in 2025-02, with the labels that each got.

#5038 Plumb transaction id into LQT vote action handlers
  crates/core/app-tests/tests/spend.rs
  crates/core/component/funding/src/action_handler/liquidity_tournament/mod.rs
  crates/core/transaction/src/transaction.rs
  crates/core/txhash/src/context.rs
Labels: consensus-breaking

#5040 distributions: implement rpc services
  Cargo.lock
  crates/core/component/distributions/Cargo.toml
  crates/core/component/distributions/src/component.rs
  crates/core/component/distributions/src/component/rpc.rs
  crates/core/component/distributions/src/component/state_key.rs
  crates/core/component/distributions/src/component/view.rs
  crates/proto/src/gen/penumbra.core.component.distributions.v1.rs
  crates/proto/src/gen/penumbra.core.component.distributions.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/distributions/v1/distributions.proto
Labels: consensus-breaking

#5044 distributions: add distributions events
  crates/core/component/distributions/src/component.rs
  crates/core/component/distributions/src/event.rs
  crates/core/component/distributions/src/lib.rs
  crates/proto/src/gen/penumbra.core.component.distributions.v1.rs
  crates/proto/src/gen/penumbra.core.component.distributions.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/distributions/v1/distributions.proto
Labels: consensus-breaking

#5045 Implement LQT reward distribution
  Cargo.lock
  crates/core/component/dex/src/component/position_manager/volume_tracker.rs
  crates/core/component/funding/Cargo.toml
  crates/core/component/funding/proptest-regressions/component/liquidity_tournament/rewards/gauge.txt
  crates/core/component/funding/src/component.rs
  crates/core/component/funding/src/component/liquidity_tournament/bank.rs
  crates/core/component/funding/src/component/liquidity_tournament/mod.rs
  crates/core/component/funding/src/component/liquidity_tournament/rewards/gauge.rs
  crates/core/component/funding/src/component/liquidity_tournament/rewards/mod.rs
  crates/core/component/funding/src/component/liquidity_tournament/votes/mod.rs
  crates/core/component/funding/src/component/state_key.rs
  crates/core/num/src/percentage/mod.rs
Labels: consensus-breaking

#5048 ci: slightly faster rust checks
  .github/workflows/buf-pull-request.yml
  .github/workflows/buf-push.yml
  .github/workflows/containers.yml
  .github/workflows/docs-lint.yml
  .github/workflows/notes.yml
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .github/workflows/smoke.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/bin/pmonitor/Cargo.toml
  crates/bin/pmonitor/tests/common/mod.rs
  crates/bin/pmonitor/tests/network_integration.rs
  deployments/compose/process-compose-dev-tooling.yml
  deployments/compose/process-compose-metrics.yml
  deployments/compose/process-compose-postgres.yml
  deployments/compose/process-compose-smoke-test.yml
  deployments/compose/process-compose.yml
  deployments/scripts/install-grpcurl
  deployments/scripts/run-local-devnet.sh
  deployments/scripts/smoke-test.sh
  justfile
Labels: A-CI/CD

#5049 LQT: reimplementation with minimal in-memory state
  crates/core/component/funding/src/action_handler/liquidity_tournament/mod.rs
  crates/core/component/funding/src/component/liquidity_tournament/rewards/gauge.rs
  crates/core/component/funding/src/component/liquidity_tournament/rewards/mod.rs
  crates/core/component/funding/src/component/liquidity_tournament/votes/mod.rs
  crates/core/component/funding/src/component/state_key.rs
Labels: consensus-breaking

#5052 Add compact block cost to LQT vote action
  crates/core/transaction/src/gas.rs
Labels: consensus-breaking

#5056 ci: make workflows runnable ad-hoc
  .github/workflows/buf-pull-request.yml
  .github/workflows/buf-push.yml
  .github/workflows/docs-lint.yml
  .github/workflows/notes.yml
Labels: A-CI/CD

#5051 dex: relax inner guard for withdrawn LP updates
  crates/core/component/dex/src/component/position_manager.rs
Labels: consensus-breaking, A-dex

#5061 funding: implement rpc services
  Cargo.lock
  crates/core/component/distributions/src/component.rs
  crates/core/component/funding/Cargo.toml
  crates/core/component/funding/src/component.rs
  crates/core/component/funding/src/component/liquidity_tournament/nullifier/mod.rs
  crates/core/component/funding/src/component/rpc.rs
  crates/proto/src/gen/penumbra.core.component.funding.v1.rs
  crates/proto/src/gen/penumbra.core.component.funding.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/core/component/funding/v1/funding.proto
Labels: consensus-breaking

#5064 view service: Implement LQT rpcs (follow-up)
  crates/proto/src/gen/penumbra.view.v1.rs
  crates/proto/src/gen/penumbra.view.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/view/v1/view.proto
Labels: consensus-breaking

#5071 LQT: fix start position <=> epoch comparison
  crates/core/component/funding/src/action_handler/liquidity_tournament/mod.rs
Labels: consensus-breaking

#5073 chore: bump app version 9 -> 10
  COMPATIBILITY.md
  Cargo.lock
  Cargo.toml
  crates/bin/pd/Cargo.toml
  crates/bin/pmonitor/Cargo.toml
  crates/core/app/src/app_version.rs
  crates/core/app/src/app_version/component.rs
  crates/custody/Cargo.toml
Labels: consensus-breaking

#5074 pd: add no-op migration for APP_VERSION 10
  Cargo.lock
  Cargo.toml
  crates/bin/pd/Cargo.toml
  crates/bin/pd/src/main.rs
  crates/bin/pd/src/migrate.rs
  crates/bin/pd/src/migrate/mainnet3.rs
  crates/bin/pmonitor/Cargo.toml
  crates/core/app/src/app_version/component.rs
  crates/custody/Cargo.toml
Labels: consensus-breaking

#5075 Bugfix: LQT effect hash calculation
  crates/core/component/funding/src/liquidity_tournament/action/mod.rs
Labels: consensus-breaking

#5077 lqt: wire action handlers for vote action
  crates/core/app/src/action_handler/actions.rs
Labels: consensus-breaking

#5080 tpr: extend to lqt actions
  crates/proto/src/gen/penumbra.view.v1.rs
  crates/proto/src/gen/penumbra.view.v1.serde.rs
  crates/proto/src/gen/proto_descriptor.bin.no_lfs
  proto/penumbra/penumbra/view/v1/view.proto
Labels: consensus-breaking

#5085 LQT: adjust budget every block
  crates/core/component/distributions/src/component.rs
  crates/core/component/distributions/src/event.rs
Labels: consensus-breaking
